- name: varibles
  hosts: web
  vars:
    Name: "Kiran"
    Course: "DevOps"
    Trainer: "sivakumar"  
  tasks: 
  - name: checking variables
    ansible.builtin.debug:
       msg: "Hi {{Name}} is learning {{Course}} with {{Trainer}}"