- name: variables from TASK level
  hosts: web
  vars:
    Name: "Kiran"
    Course: "Devops"
    Trainer: "siva"
  tasks:
  - name: check variables
    vars:
      Name: "Kiran Kumar"
    ansible.builtin.debug:
     msg: "Hi {{Name}} is learning {{Course}} with {{Trainer}}"