- name: variables using prompt 
  hosts: web 
  vars_prompt:
  - name: Username
    prompt: please enter username
    private: false
  - name: Passsword
    prompt: please enter password
    private: false
  tasks:
  - name: print and run prompt variables
    ansible.builtin.debug:
      msg: "Username is {{Username}}, Password is {{Password}}"