- name: cart component
  hosts: cart
  become: yes
  tasks: 
  - name: disable and enable nodejs 
    ansible.builtin.shell: "dnf module disable nodejs -y ; dnf module enable nodejs:18 -y"

  - name: install nodejs
    ansible.builtin.package:
       name: nodejs
       state: present

  - name: crete roboshop cart
    ansible.builtin.user:
       name: roboshop     

  - name: Recusively remove app directory
    ansible.builtin.file:
        path: /app
        state: absent

  - name: create app directory
    ansible.builtin.file:
        path: /app
        state: directory

  - name: download cart application
    ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp

  - name: unzip cart application
    ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy cart service
    ansible.builtin.copy:
       src: cart.service
       dest: /etc/systemd/system/cart.service
  
  - name: demon reload and start 
    ansible.builtin.systemd_service:
        daemon_reload: true

  - name: restart cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes

  
  