- name: dispatch component 
  hosts: dispatch
  become: yes
  tasks: 
  - name: install golang 
    ansible.builtin.dnf: 
        name: golang 
        state: present

  - name: crete roboshop user
    ansible.builtin.user:
       name: roboshop     

  - name: Recusively remove app directory
    ansible.builtin.file:
        path: /app
        state: absent

  - name: create app directory
    ansible.builtin.file:
        path: /app
        state: directory

  - name: download dispatch application
    ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
        dest: /tmp

  - name: unzip dispatch application
    ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: yes
  
  - name: download dependencies and build software
    ansible.builtin.command: go mod init dispatch

  - name: download dependencies 
    ansible.builtin.command: go get

  - name: build software
    ansible.builtin.command: go build

  - name: copy dispatch service
    ansible.builtin.copy:
       src: dispatch.service
       dest: /etc/systemd/system/dispatch.service

  - name: daemon reload and start 
    ansible.builtin.systemd_service:
        daemon_reload: true

  - name: restart dispatch
    ansible.builtin.service:
      name: dispatch
      state: restarted
      enabled: yes 

 