- name: payment component 
  hosts: payment
  become: yes
  tasks:
  - name: install python 
    ansible.builtin.dnf:
        name: "{{item}}"
        state: present
    loop:
    - python36 
    - gcc 
    - python3-devel

  - name: create roboshop user
    ansible.builtin.user: 
        name: roboshop

  - name: recusively remove app directory 
    ansible.builtin.file:
        path: /app
        state: absent

  - name: create app directory
    ansible.builtin.file:
        path: /app
        state: directory

  - name: download payment application
    ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/payment.zip
        dest: /tmp

  - name: unzip payment application
    ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes

  - name: install dependencies
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app

  - name: copy payment service
    ansible.builtin.copy:
       src: payment.service
       dest: /etc/systemd/system/payment.service

  - name: daemon reload and start 
    ansible.builtin.systemd_service:
        daemon_reload: true   

  - name: restart payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes
   



  