- name: user component
  hosts: user
  become: yes
  tasks: 
  - name: disable and enable nodejs 
    ansible.builtin.shell: "dnf module disable nodejs -y ; dnf module enable nodejs:18 -y"

  - name: install nodejs
    ansible.builtin.package:
       name: nodejs
       state: present

  - name: crete roboshop user
    ansible.builtin.user:
       name: roboshop     

  - name: Recusively remove app directory
    ansible.builtin.file:
        path: /app
        state: absent

  - name: create app directory
    ansible.builtin.file:
        path: /app
        state: directory

  - name: download user application
    ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp

  - name: unzip user application
    ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy user service
    ansible.builtin.copy:
       src: user.service
       dest: /etc/systemd/system/user.service
  
  - name: demon reload and start 
    ansible.builtin.systemd_service:
        daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb client
    ansible.builtin.package:
       name: mongodb-org-shell
       state: present

  - name: get that user count
    ansible.builtin.command: mongo --host mongodb.tssdevops.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'  
    register: user_count

  # - name: print the count 
  #   ansible.builtin.debug:
  #     msg: "product count: {{user_count}}"  

  - name: load schema 
    ansible.builtin.command: mongo --host mongodb.tssdevops.online < /app/schema/user.js
    when: user_count.stdout == "0"
  

  - name: restart user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes

  
  